Add: Modal components
onCondition/onCondition-client pull request #42
Opened 2021-09-05 14:17 UTC by Soodev20

모달 컴포넌트입니다.

componentLogic 폴더에 모달 버튼을 눌렀을 때 실행될 로직을 넣고, 
component 폴더에 styled-components와 모달 객체를 리턴하는 파일을 넣어두었습니다.

오른쪽 버튼은 언제나 Close로 지정되어 있습니다.

2021-09-05 14:36 UTC, hayjo requested changes
디자인 엄청 공들여서 작성해주신 것 같아요!! 감사합니다👏

2021-09-05 14:36 UTC, hayjo commented on src/componentLogic/Modal.jsx
> +import ModalComponent from "../components/modalComponent";
이 파일도 컴포넌트니까 파일명 대문자로 작성하는 건 어떨까요?

2021-09-05 14:36 UTC, hayjo commented on src/componentLogic/Modal.jsx
> +  const onConfirm = () => {
화살표함수를 쓰시는군요..! 저희 이거 정하면 좋을 것 같습니다!

2021-09-05 14:36 UTC, hayjo commented on src/components/modalComponent.jsx
> +  z-index:100;
```suggestion
  z-index: 100;
```

스타일린트가 작동을 잘 안하는 것 같네요. 이 부분 수정해서 PR 만들어야겠습니다🥲

2021-09-05 14:36 UTC, hayjo commented on src/componentLogic/Modal.jsx
> +        innerText="아이고어아고"
innerText는 위에서 내려주는 prop인가요??

2021-09-05 18:26 UTC, Soodev20 commented on src/componentLogic/Modal.jsx
> +  const onConfirm = () => {
음.. 아직은 논의한 바가 없으니 화살표함수는 저희가 사용하던 선언식으로 변경해놓겠습니다!

2021-09-05 18:28 UTC, Soodev20 commented on src/components/modalComponent.jsx
> +  z-index:100;
넵... 저 다른 부분에서 trailing commas 가 잡히지 않은 것을 발견했습니다...!

2021-09-05 18:32 UTC, Soodev20 commented on src/componentLogic/Modal.jsx
> +        innerText="아이고어아고"
넵!
Modal.jsx에서 ModalComponent.jsx로 내려주는 구조로 작성했습니다.
잠시 후에 prop을 전달하는 부분 역시 다시 한 번 명시적으로 문서화 하는 것이 어떨까요?

2021-09-05 18:45 UTC, hayjo commented on src/componentLogic/Modal.jsx
> +  const onConfirm = () => {
혹시 쓰시는 기준이 있다면 공유되면 좋을 것 같습니다!

2021-09-05 18:48 UTC, hayjo commented on src/components/modalComponent.jsx
> +  z-index:100;
해당 이슈 PR 머지되었습니다! 최근에 작업된 부분이라 이후에 dev 브랜치 pull 받으실 때에는 적용되어 있을 거예요! 확인 감사합니다😃

2021-09-05 18:49 UTC, hayjo commented on src/componentLogic/Modal.jsx
> +        innerText="아이고어아고"
넵 어떤 경우에 prop으로 하고 어떤 경우에 컴포넌트가 직접 갖고 있을지도 논의해보는 게 좋겠네요! (모달은 위에서 받아야하는 경우일 것 같긴 합니다만)

2021-09-05 23:32 UTC, geewoo94 reviewed
코멘트 확인 부탁드립니다.

2021-09-05 23:32 UTC, geewoo94 commented on src/components/modalComponent.jsx
> +  if (!modal) return null;
modal이라는 prop이 들어오지 않으면 해당 컴포는트는 아무런 역할도 하지 않는군요. 컴포넌트를 사용할지 말지는 외부에서 결정해야하고 컴포넌트는 단순히 그려주는 역할만 하면 좋을것 같습니다. 

```javascript
{modal && <ModalComponent />}
```

2021-09-05 23:32 UTC, geewoo94 commented on src/components/modalComponent.jsx
> +  innerText: "Text",
적절하지 않은 초기값 같습니다. isRequired 필드를 주는것이 더 적절할거 같아요.

2021-09-05 23:32 UTC, geewoo94 commented on src/componentLogic/Modal.jsx
> +  const [modal, setModal] = useState(true);
불리언값인데 네이밍 컨벤션이 조금 아쉬운거같은데 isModalOn 처럼 불리언값임을 유추할 수있는 이름은 어떨까요?

2021-09-05 23:32 UTC, geewoo94 commented on src/components/modalComponent.jsx
> +  background-color: rgba(138, 214, 204, 0.9);
컬러값들 상수로 관리하시면 좋을거 같습니다. styled-compoent의 theme이요!

2021-09-05 23:32 UTC, geewoo94 commented on src/components/modalComponent.jsx
> +  top: calc(20vh);
calc(20vh)와 그냥 20vh는 다르게 동작하나요?

2021-09-05 23:32 UTC, geewoo94 commented on src/components/modalComponent.jsx
> +  z-index: 10;
z-index값이 1000, 100, 10 무분별하게 사용되고 있는거같아요. 제 생각엔 ModalWrapper이외의 태그들은 z-index없이 처리 가능할거 같습니다. 구현할때 z-index를 사용하지 않았을 때 이슈 사항이 있었나요?

2021-09-07 09:50 UTC, Soodev20 commented on src/components/modalComponent.jsx
> +  top: calc(20vh);
vh와 wh 는 언제나 계산되기때문에 결국에는 같은 값이라고 합니다. 수정하였습니다.

2021-09-07 13:05 UTC, closed without merging